### PR TITLE
fix a bug before response from cache

### PR DESCRIPTION
**Pull request by wonderbeyond**

### CODE REVIEW

**Comment by huchenme** [comment]
thanks @wonderbeyond 👍

**Comment by wonderbeyond** [comment]
Did the new release been deployed to **now.sh**? I'm still experiencing slow response.

**Comment by huchenme** [comment]
@wonderbeyond yeah just deployed. Is it getting better now?

**Comment by huchenme** [comment]
@wonderbeyond Thanks a lot, I could notice myself it is so much faster now!

**Pull request merged**
