### PR TITLE
fix: new GitHub page change

### LINKED ISSUE #73: Github updated their HTML structure
The api always returns "0" for stars

### PR DESCRIPTION
**Pull request by theArgex**
Fix forks and stars showing zero
closes #73

### CODE REVIEW

**Comment by huchenme** [comment]
Thanks very much this this PR, This PR fixes the stars 0 issue but the fork number is still 0, could you help fix that as well?

**Comment by theArgex** [comment]
> Thanks very much for this PR, This PR fixes the stars 0 issue but the fork number is still 0, could you help fix that as well?

Of course. Didn't notice it before because I don't show the forks number on my website :D

**Comment by theArgex** [comment]
@huchenme Made a new commit. Forks should work now

**Pull request merged**
